# Generated by Django 5.0.4 on 2024-10-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_specialty_groups_group_specialty'),
        ('users', '0005_customuser_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.AddField(
            model_name='customuser',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='users', to='myapp.department'),
        ),
    ]
