# Generated by Django 5.0.4 on 2024-10-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='group',
        ),
        migrations.AddField(
            model_name='specialty',
            name='groups',
            field=models.ManyToManyField(related_name='specialties', to='myapp.group', verbose_name='Групи'),
        ),
    ]
