# Generated by Django 5.0.4 on 2024-10-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_specialty_group_specialty_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='myapp.specialty', verbose_name='Спеціальність'),
        ),
    ]
