# Generated by Django 5.0.4 on 2024-11-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_specialty_groups_group_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='department',
        ),
        migrations.CreateModel(
            name='SpecialtyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='myapp.department', verbose_name='Кафедра')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='myapp.specialty', verbose_name='спеціальність')),
            ],
            options={
                'unique_together': {('specialty', 'department')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='groups', to='myapp.specialtydepartment', verbose_name='Спеціальності'),
        ),
    ]
