# Generated by Django 5.0.4 on 2024-11-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_group_specialty_remove_specialty_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='total_time',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
