# Generated by Django 5.1.3 on 2025-04-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_discipline_total_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson_visit',
            unique_together={('email', 'date', 'discipline', 'lesson', 'group')},
        ),
    ]
